name: learnmofox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
      - sphinx~=3.3.1
      - sphinx-book-theme~=0.0.39
      - sphinx-autodoc-typehints~=1.11.1
      - sphinx-copybutton~=0.3.1
      - scikit-learn<0.23>=0.22
      - git+https://github.com/kjappelbaum/hyperopt-sklearn.git#egg=hpsklearn
      - imbalanced-learn<0.7>=0.6
      - ml_insights~=0.0.21
      - mlxtend~=0.17.2
      - pandas~=1.0
      - click~=7.1
      - comet~=3.1
      - tqdm~=4.48
      - dask~=2.14
      - shap~=0.35
